/*
 * Simple Twitter API
 *
 * API for a simple Twitter-like application.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmd

type Follow struct {

	UserId string `json:"user_id,omitempty"`

	FollowId string `json:"follow_id,omitempty"`
}
