/*
 * Simple Twitter API
 *
 * API for a simple Twitter-like application.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmd

type FollowsBody struct {

	UserId string `json:"user_id"`

	FollowId string `json:"follow_id"`
}
