/*
 * Simple Twitter API
 *
 * API for a simple Twitter-like application.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmd

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"CreateFollow",
		strings.ToUpper("Post"),
		"/v1/follows",
		CreateFollow,
	},

	Route{
		"CreateTweet",
		strings.ToUpper("Post"),
		"/v1/tweets",
		CreateTweet,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/v1/users",
		CreateUser,
	},

	Route{
		"GetTweet",
		strings.ToUpper("Get"),
		"/v1/tweets/{tweet_id}",
		GetTweet,
	},

	Route{
		"GetUser",
		strings.ToUpper("Get"),
		"/v1/users/{user_id}",
		GetUser,
	},

	Route{
		"GetFollowersForUser",
		strings.ToUpper("Get"),
		"/v1/followers",
		GetFollowersForUser,
	},

	Route{
		"GetFollowsForUser",
		strings.ToUpper("Get"),
		"/v1/follows",
		GetFollowsForUser,
	},
}
