version: "3.8"

services:
  mysql_server:
    container_name: mysql_server
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql_test
        target: /var/lib/mysql
volumes:
  mysql_test:
    name: mysql_test
